"""create webhook ingestion tables

Revision ID: b16dc8fb431e
Revises:
Create Date: 2026-08-20 18:23:26.747965

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b16dc8fb431e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("provider_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("raw_body_sha256", sa.String(length=64), nullable=False),
        sa.Column("sanitized_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("processing_result", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "processing_result IN ('processed', 'ignored')",
            name=op.f("ck_webhook_events_processing_result_allowed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint("provider_event_id", name=op.f("uq_webhook_events_provider_event_id")),
    )
    op.create_index("ix_webhook_events_event_name", "webhook_events", ["event_name"], unique=False)
    op.create_index(
        "ix_webhook_events_provider_created_at",
        "webhook_events",
        ["provider_created_at"],
        unique=False,
    )
    op.create_index(
        "ix_webhook_events_received_at", "webhook_events", ["received_at"], unique=False
    )
    op.create_table(
        "payment_observations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("webhook_event_id", sa.UUID(), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=255), nullable=False),
        sa.Column("provider_order_id", sa.String(length=255), nullable=True),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("payment_status", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_source", sa.String(length=100), nullable=True),
        sa.Column("error_step", sa.String(length=100), nullable=True),
        sa.Column("error_reason", sa.String(length=100), nullable=True),
        sa.Column("provider_event_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_payment_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_payment_observations_currency_iso_shape")
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_payment_observations_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["webhook_event_id"],
            ["webhook_events.id"],
            name=op.f("fk_payment_observations_webhook_event_id_webhook_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_observations")),
        sa.UniqueConstraint(
            "webhook_event_id", name=op.f("uq_payment_observations_webhook_event_id")
        ),
    )
    op.create_index(
        "ix_payment_observations_provider_event_created_at",
        "payment_observations",
        ["provider_event_created_at"],
        unique=False,
    )
    op.create_index(
        "ix_payment_observations_provider_order_id",
        "payment_observations",
        ["provider_order_id"],
        unique=False,
    )
    op.create_index(
        "ix_payment_observations_provider_payment_id",
        "payment_observations",
        ["provider_payment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payment_observations_provider_payment_id", table_name="payment_observations")
    op.drop_index("ix_payment_observations_provider_order_id", table_name="payment_observations")
    op.drop_index(
        "ix_payment_observations_provider_event_created_at", table_name="payment_observations"
    )
    op.drop_table("payment_observations")
    op.drop_index("ix_webhook_events_received_at", table_name="webhook_events")
    op.drop_index("ix_webhook_events_provider_created_at", table_name="webhook_events")
    op.drop_index("ix_webhook_events_event_name", table_name="webhook_events")
    op.drop_table("webhook_events")
    # ### end Alembic commands ###
