"""create live scoring tables

Revision ID: eb0e41522f43
Revises: b16dc8fb431e
Create Date: 2026-08-22 16:11:50.229427

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb0e41522f43"
down_revision: str | Sequence[str] | None = "b16dc8fb431e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("checkout_id", sa.String(length=64), nullable=False),
        sa.Column("session_token", sa.String(length=64), nullable=False),
        sa.Column("payment_instrument_token", sa.String(length=64), nullable=False),
        sa.Column("customer_token", sa.String(length=64), nullable=True),
        sa.Column("device_token", sa.String(length=64), nullable=True),
        sa.Column("network_token", sa.String(length=64), nullable=True),
        sa.Column("amount_subunits", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("calibrated_probability", sa.Numeric(precision=20, scale=18), nullable=True),
        sa.Column("decision_threshold", sa.Numeric(precision=20, scale=18), nullable=False),
        sa.Column("risk_decision", sa.String(length=16), nullable=True),
        sa.Column("action", sa.String(length=16), nullable=True),
        sa.Column("fail_safe_reason", sa.String(length=64), nullable=True),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("feature_dataset_id", sa.String(length=64), nullable=False),
        sa.Column("feature_schema_version", sa.String(length=16), nullable=False),
        sa.Column("feature_engine_version", sa.String(length=16), nullable=False),
        sa.Column("razorpay_order_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('allow', 'review', 'deny')", name=op.f("ck_risk_decisions_action_allowed")
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_risk_decisions_currency_iso_shape")
        ),
        sa.CheckConstraint(
            "risk_decision IN ('allow', 'deny')",
            name=op.f("ck_risk_decisions_risk_decision_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'final')", name=op.f("ck_risk_decisions_status_allowed")
        ),
        sa.CheckConstraint(
            "amount_subunits >= 1", name=op.f("ck_risk_decisions_amount_subunits_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
        sa.UniqueConstraint("event_id", name=op.f("uq_risk_decisions_event_id")),
    )
    op.create_index("ix_risk_decisions_action", "risk_decisions", ["action"], unique=False)
    op.create_index(
        "ix_risk_decisions_checkout_id", "risk_decisions", ["checkout_id"], unique=False
    )
    op.create_index(
        "ix_risk_decisions_merchant_id", "risk_decisions", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_risk_decisions_occurred_at", "risk_decisions", ["occurred_at"], unique=False
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("risk_decision_id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("checkout_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status = 'pending'", name=op.f("ck_review_items_status_allowed")),
        sa.ForeignKeyConstraint(
            ["risk_decision_id"],
            ["risk_decisions.id"],
            name=op.f("fk_review_items_risk_decision_id_risk_decisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_items")),
        sa.UniqueConstraint("risk_decision_id", name=op.f("uq_review_items_risk_decision_id")),
    )
    op.create_index("ix_review_items_created_at", "review_items", ["created_at"], unique=False)
    op.create_index("ix_review_items_merchant_id", "review_items", ["merchant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_items_merchant_id", table_name="review_items")
    op.drop_index("ix_review_items_created_at", table_name="review_items")
    op.drop_table("review_items")
    op.drop_index("ix_risk_decisions_occurred_at", table_name="risk_decisions")
    op.drop_index("ix_risk_decisions_merchant_id", table_name="risk_decisions")
    op.drop_index("ix_risk_decisions_checkout_id", table_name="risk_decisions")
    op.drop_index("ix_risk_decisions_action", table_name="risk_decisions")
    op.drop_table("risk_decisions")
    # ### end Alembic commands ###
