"""create explanation table

Revision ID: 0003explanations
Revises: eb0e41522f43
Create Date: 2026-08-23 03:11:14.795842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003explanations"
down_revision: str | Sequence[str] | None = "eb0e41522f43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_decision_explanations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("risk_decision_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.String(length=400), nullable=True),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("caveat", sa.String(length=300), nullable=True),
        sa.Column("failure_reason", sa.String(length=64), nullable=True),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'ready' OR summary IS NOT NULL",
            name=op.f("ck_risk_decision_explanations_ready_requires_summary"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'failed', 'rejected')",
            name=op.f("ck_risk_decision_explanations_status_allowed"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('failed', 'rejected') OR failure_reason IS NOT NULL",
            name=op.f("ck_risk_decision_explanations_terminal_failure_requires_reason"),
        ),
        sa.CheckConstraint(
            "attempt_number >= 1",
            name=op.f("ck_risk_decision_explanations_attempt_number_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["risk_decision_id"],
            ["risk_decisions.id"],
            name=op.f("fk_risk_decision_explanations_risk_decision_id_risk_decisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decision_explanations")),
        sa.UniqueConstraint(
            "risk_decision_id", "attempt_number", name="explanation_attempt_unique"
        ),
    )
    op.create_index(
        "ix_risk_decision_explanations_risk_decision_id",
        "risk_decision_explanations",
        ["risk_decision_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_risk_decision_explanations_risk_decision_id", table_name="risk_decision_explanations"
    )
    op.drop_table("risk_decision_explanations")
    # ### end Alembic commands ###
